### ISSUE TITLE
Java. lang. OutOfMemoryError: 

### ISSUE THREAD

**Issue by wangyi1573** [XDream8/revanced-creator#34]
An internal overflow error may occur when repairing TikTok,
Java. lang. OutOfMemoryError: Failed to allocate a 48 byte allocation with 1428208 free bytes and 1394KB until OOM, target footprint 536870912, growth limit 536870912; Giving up on allocation because<1% of heap free after GC
At java. nio. CharBuffer. allocate (CharBuffer. java: 172)
Adding - Xmx512m - Xms512m after the Java command can solve the problem

**Comment by XDream8** [comment]
I will update revanced-creator soon wait for it.

changed things:
- replaced environment variables with flags
- code cleanups/improvements

**Comment by wangyi1573** [comment]
After trying to add this code, I still encountered errors when compiling TikTok, unable to complete the compilation, or successfully compiled, but the modifications seemed to be invalid

**Comment by wangyi1573** [comment]
INFO: Loading patches 
INFO: Decoding app manifest 
WARNING: Downloads is incompatible with version 27.8.3. This patch is only compatible with version 30.8.4;30.8.4 
WARNING: Hide ads is incompatible with version 27.8.3. This patch is only compatible with version 30.8.4;30.8.4 
INFO: SIM spoof excluded 
WARNING: Settings is incompatible with version 27.8.3. This patch is only compatible with version 30.8.4;30.8.4 
INFO: Export all activities excluded 
INFO: Remove screen capture restriction excluded 
INFO: Remove screenshot restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Predictive back gesture excluded 
INFO: Override certificate pinning excluded 
INFO: Change package name excluded 
INFO: Enable Android debugging excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Executing patches 
INFO: Disable login requirement succeeded 
INFO: Feed filter succeeded 
INFO: Fix Google login succeeded 
INFO: Playback speed succeeded 
SEVERE: Show seekbar failed:
app.revanced.patcher.patch.PatchException: 'Show seekbar' depends on 'ShowSeekbarPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve SetSeekBarShowTypeFingerprint
        at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:22)
        at app.revanced.patches.tiktok.interaction.seekbar.ShowSeekbarPatch.execute(ShowSeekbarPatch.kt:41)
        at app.revanced.patches.tiktok.interaction.seekbar.ShowSeekbarPatch.execute(ShowSeekbarPatch.kt:12)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:201)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:224)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:223)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:201)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:224)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:223)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
 
INFO: Compiling modified dex files
