### ISSUE TITLE
how can i fix it

### ISSUE THREAD

**Issue by kawinpattanai** [XDream8/revanced-creator#4]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_42901427201457999071617787551035283271.tmp, compile, --dir, /root/Desktop/revanced/revanced-cache/res, --legacy, -o, /root/Desktop/revanced/revanced-cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:372)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
	at app.revanced.patcher.Patcher.save(Patcher.kt:199)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:164)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 132): [/tmp/brut_util_Jar_42901427201457999071617787551035283271.tmp, compile, --dir, /root/Desktop/revanced/revanced-cache/res, --legacy, -o, /root/Desktop/revanced/revanced-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:368)
	... 13 more

**Comment by XDream8** [comment]
Are you trying to run this on termux?

revanced-cli does not support android yet

**Comment by XDream8** [comment]
I get the same result on my phone

**Comment by kawinpattanai** [comment]
oh ok
